//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 02:49:15 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://orbcit.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cit.orb.soap;
